version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports: 
      - '$PORT:$PORT'
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_DB: $DB_NAME
    volumes:
      - $HOME/volumes/postgres/dialog-iterview:/data/postgres/dialog-interview:rw%

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - $HOME/volumes/rabbitmq/data/:/var/lib/rabbitmq/
        - $HOME/volumes/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge